[package]
name = "rust_sdk"
version = "0.0.1"
edition = "2021"
publish = false
build = false

[[bin]]
name = "generate"
path = "generate.rs"
required-features = ["build_deps"]

[dependencies]
base64 = { version = "0.22.0", default-features = false, features = ["std"] }
hex = { version = "0.4.3", default-features = false, features = ["std"] }
p256 = { version = "0.13.2", default-features = false, features = ["ecdsa"] }
serde = { version = "1.0.197", default-features = false, features = ["std", "derive"] }
serde_json = { version = "1.0.115", default-features = false, features = ["std"] }
thiserror = { version = "1.0.58", default-features = false }
bytes = { version = "1.6.0", default-features = false }
prost = { version = "0.12.6" }
prost-types = { version = "0.12.6" }
prost-build = { version = "0.12.6", default-features = false, optional = true }
reqwest = { version = "0.12.4", default-features = false, features = ["json"] }
dotenv = "0.15.0"
pbjson-build = "0.6.2"
pbjson-types = "0.6.0"
pbjson = "0.6.0"

[features]
build_deps = ["prost-build"]

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }

[patch.crates-io]
pbjson-build = { git = "https://github.com/mountainpath9/pbjson.git", branch="mpath-fix-result-scoping" }
